# Generated by Django 4.2 on 2024-11-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_payment_course_payment_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
