# Generated by Django 4.2 on 2024-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
